version: "3.7"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_CLIENT_ID=${CLIENT_ID}
    depends_on:
      - backend
    command: npm start

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
