# Generated by Django 3.2.5 on 2022-02-11 17:23

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPokerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100, null=True)),
                ('org_name', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'planningPokerSession',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('VOTING', 'VOTING'), ('DISCUSSING', 'DISCUSSING'), ('SAVING', 'SAVING'), ('FINISHED', 'FINISHED')], default='NOT_STARTED', max_length=50, protected=True, verbose_name='State of the current round in the Planning Poker Session')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(default='', max_length=65536, null=True)),
                ('github_issue_number', models.IntegerField(null=True)),
                ('note', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(None, 'not estimated'), (1, '1'), (2, '2'), (3, '3'), (5, '5'), (8, '8'), (13, '13'), (20, '20'), (40, '40'), (100, 'the task is too large or complex, we need to reconsider it'), (99, "I'm unsure, we might need to clarify the requirements")])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.task')),
            ],
        ),
    ]
