# Generated by Django 3.2.5 on 2021-11-16 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPokerSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100, null=True)),
                ('org_name', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'planningPokerSession',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(default='', max_length=5000, null=True)),
                ('hours', models.PositiveSmallIntegerField(choices=[(None, 'not estimated'), (1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (5, '5 hours'), (8, '8 hours'), (13, '13 hours'), (20, '20 hours'), (40, '40 hours'), (100, 'the task is too large or complex, we need to reconsider it'), (99, "I'm unsure, we might need to clarify the requirements")], null=True)),
                ('is_decided', models.BooleanField(blank=True, default=False, null=True)),
                ('github_issue_number', models.IntegerField(blank=True, null=True)),
                ('is_imported', models.BooleanField()),
                ('planningpokersession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='poker.planningpokersession')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.PositiveSmallIntegerField(choices=[(None, 'not estimated'), (1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (5, '5 hours'), (8, '8 hours'), (13, '13 hours'), (20, '20 hours'), (40, '40 hours'), (100, 'the task is too large or complex, we need to reconsider it'), (99, "I'm unsure, we might need to clarify the requirements")])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planningpokersession',
            name='current_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_session', to='poker.task', verbose_name='The task currently being estimated'),
        ),
        migrations.AddField(
            model_name='planningpokersession',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderator_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningpokersession',
            name='voters',
            field=models.ManyToManyField(related_name='poker_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='cannot cast a vote twice on same task'),
        ),
    ]
