# Generated by Django 3.2.5 on 2021-11-14 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPokerSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'planningPokerSession',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('hours', models.PositiveSmallIntegerField(choices=[(None, 'not estimated'), (1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (5, '5 hours'), (8, '8 hours'), (13, '13 hours'), (20, '20 hours'), (40, '40 hours'), (100, 'the task is too large or complex, we need to reconsider it'), (99, "I'm unsure, we might need to clarify the requirements")], null=True)),
                ('is_decided', models.BooleanField(blank=True, default=False, null=True)),
                ('github_issue_number', models.IntegerField(blank=True, null=True)),
                ('is_imported', models.BooleanField()),
                ('planningpokersession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='poker.planningpokersession')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.AddField(
            model_name='planningpokersession',
            name='current_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_session', to='poker.task', verbose_name='The task currently being estimated'),
        ),
    ]
