# Generated by Django 3.2.5 on 2021-11-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningpokersession',
            name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='planningpokersession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='poker.planningpokersession'),
        ),
    ]
