# Generated by Django 3.2.5 on 2022-02-09 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningpokersession',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planningpokersession',
            name='voters',
            field=models.ManyToManyField(related_name='voter_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
