# Generated by Django 3.2.5 on 2021-11-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='github_issue_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_decided',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
