# Generated by Django 3.2.5 on 2021-12-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20211116_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='estimate',
            new_name='value',
        ),
    ]
