# Generated by Django 3.2.5 on 2022-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_rename_estimate_vote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
