# Generated by Django 3.2.5 on 2022-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_auto_20220111_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
