# Generated by Django 3.2.5 on 2022-01-26 16:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_task_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='planningpokersession',
            new_name='planning_poker_session',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_decided',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_imported',
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('VOTING', 'VOTING'), ('DISCUSSING', 'DISCUSSING'), ('SAVING', 'SAVING'), ('FINISHED', 'FINISHED')], default='NOT_STARTED', max_length=50, protected=True, verbose_name='State of the current round in the Planning Poker Session'),
        ),
    ]
