# Generated by Django 3.2.5 on 2022-02-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_auto_20220126_1632'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='cannot cast a vote twice on same task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hours',
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(None, 'not estimated'), (1, '1'), (2, '2'), (3, '3'), (5, '5'), (8, '8'), (13, '13'), (20, '20'), (40, '40'), (100, 'the task is too large or complex, we need to reconsider it'), (99, "I'm unsure, we might need to clarify the requirements")]),
        ),
    ]
